name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build app
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact # Name of the step
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
          name: my-artifact # Name of the artifact to upload. Optional. Default is 'artifact
          path: ./ # A file, directory or wildcard pattern that describes what to upload. Required.
  Linter:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build]
    steps:
      - name: Download a single artifact # Name of the step
        uses: actions/download-artifact@v4 # Action to use
        with: # Parameters for the action
          name: my-artifact # Name of the artifact to download. Optional. If unspecified, all artifacts for the run are downloaded.
          path: .     # Destination path. Supports basic tilde expansion.  # Optional. Default is $GITHUB_WORKSPACE
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          DISABLE_ERRORS: true
        

